### ISSUE TITLE
Error 500 when using a POI in a query

### ISSUE THREAD

**Issue by jmesserli** [jmesserli/slack-publictransport#17]
When using a POI or address, the overview of connections fails.

To reproduce use "erlach, Post erlach" and wander

**Comment by jmesserli** [comment]
Problem persists

<h1>500 Internal Server Error</h1>
<h3>Cannot use object of type PegNu\Api\Model\Location as array (0)</h3>
<pre>#0 /var/www/html/slack-publictransport/index.php(97): PegNu\SlackHelper::handleInteractiveCall('827b0c3d4aa260b...', 'location', '0', '')
#1 /var/www/html/slack-publictransport/vendor/mikecao/flight/flight/core/Dispatcher.php(165): {closure}()
#2 /var/www/html/slack-publictransport/vendor/mikecao/flight/flight/core/Dispatcher.php(143): flight\core\Dispatcher::callFunction(Object(Closure), Array)
#3 /var/www/html/slack-publictransport/vendor/mikecao/flight/flight/Engine.php(311): flight\core\Dispatcher::execute(Object(Closure), Array)
#4 /var/www/html/slack-publictransport/vendor/mikecao/flight/flight/core/Dispatcher.php(196): flight\Engine->_start()
#5 /var/www/html/slack-publictransport/vendor/mikecao/flight/flight/core/Dispatcher.php(142): flight\core\Dispatcher::invokeMethod(Array, Array)
#6 /var/www/html/slack-publictransport/vendor/mikecao/flight/flight/core/Dispatcher.php(48): flight\core\Dispatcher::execute(Array, Array)
#7 /var/www/html/slack-publictransport/vendor/mikecao/flight/flight/Engine.php(64): flight\core\Dispatcher->run('start', Array)
#8 /var/www/html/slack-publictransport/vendor/mikecao/flight/flight/core/Dispatcher.php(196): flight\Engine->__call('start', Array)
#9 /var/www/html/slack-publictransport/vendor/mikecao/flight/flight/Flight.php(76): flight\core\Dispatcher::invokeMethod(Array, Array)
#10 /var/www/html/slack-publictransport/index.php(121): Flight::__callStatic('start', Array)
#11 {main}</pre>
